/* CVS $Id: $ */
package gpii.schemas;

import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from C:\eclipse\workspace\JenaTutorial\preferenceVocabular.rdf 
 * @author Auto-generated by schemagen on 25 Mrz 2014 11:49 
 */
public class UPREFS {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://gpii.org/schemas/accessibility#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    /** <p>Datatype of a preference .</p> */
    public static final Property PrefDatatype = m_model.createProperty( "http://gpii.org/schemas/accessibility#PrefDatatype" );
    
    /** <p>Name of a preference .</p> */
    public static final Property PrefName = m_model.createProperty( "http://gpii.org/schemas/accessibility#PrefName" );
    
    /** <p>Value of a preference .</p> */
    public static final Property PrefValue = m_model.createProperty( "http://gpii.org/schemas/accessibility#PrefValue" );
    
    /** <p>Value range of a preference .</p> */
    public static final Property PrefValueRange = m_model.createProperty( "http://gpii.org/schemas/accessibility#PrefValueRange" );
    
    /** <p>A user has accessibility.</p> */
    public static final Property hasPrefs = m_model.createProperty( "http://gpii.org/schemas/accessibility#hasPrefs" );
    
    /** <p>Application specific accessibility preferences of a person .</p> */
    public static final Resource Appspecific = m_model.createResource( "http://gpii.org/schemas/accessibility#Appspecific" );
    
    /** <p>Common accessibility preferences of a person.</p> */
    public static final Resource Common = m_model.createResource( "http://gpii.org/schemas/accessibility#Common" );
    
    /** <p>Preferences of a person.</p> */
    public static final Resource Preference = m_model.createResource( "http://gpii.org/schemas/accessibility#Preference" );
    
    // effectively used; to be stored permanently
    
    /** <p>User requires specific accessibility settings.</p> */
    public static final Resource User = m_model.createResource( "http://gpii.org/schemas/accessibility#User" );
    
    public static final Property requiresAT = m_model.createProperty( "http://gpii.org/schemas/accessibility#requiresAT" );
    
    // to distinguish between preferred AT (explicitly though user voting) and used AT (implicitly through app-specific prefs)
    public static final Property prefersAT = m_model.createProperty( "http://gpii.org/schemas/accessibility#prefersAT" );
    
    public static final Resource Environment = m_model.createResource( "http://gpii.org/schemas/accessibility#Environment" );
    
    public static final Resource MultipleSolutionsConflict = m_model.createResource( "http://gpii.org/schemas/accessibility#MultipleSolutionsConflict" );
    
    // class to describe accessibility conflicts
    public static final Property accessibilityConflict = m_model.createProperty( "http://gpii.org/schemas/accessibility#accessibilityConflict" );
    
    // class to describe certain assistive technology classes  
    public static final Resource ATType = m_model.createResource( "http://gpii.org/schemas/accessibility#ATType" );
    
    public static final Property applyATType = m_model.createProperty( "http://gpii.org/schemas/accessibility#applyATType" );
    
    public static final Property applyATProduct = m_model.createProperty( "http://gpii.org/schemas/accessibility#applyATProduct" );
    
}
